BrightspaceUI/intl

src/number/format-decimal.js
src/number/format-positive-integer.js
test/number/format-decimal.js

**Fix formatting of really small decimals**
Small decimals, expressed in scientific/exponential notation, weren't being handled correctly and would result in totally broken results.
eg: `1e-9` would become `0.-9`
This change will put the appropriate number of zeros before the significant digits when scientific notation is detected.
**Handle numbers greater than 32-bit integers**
OR-ing the number against `0` would OR it against a 32-bit integer, causing issues with numbers longer than 32-bits.
eg: `10000000000 | 0 == 1410065408`
`Math.trunc()` simply drops the decimal from a number, which appeared to be the intention of OR-ing with 0.

Jtarka/decimal format/large and small numbers

---

README.md
lib/dateTime.js
test/dateTime.js

~~`convertUTCToLocalDateTime` takes a UTC date (e.g., `new Date(Date.UTC(2015, ... )`) and returns a `Date` with year/month/day/hour/minute/second corresponding to the `data-timezone` identifier (e.g., `America/Toronto`). This can then be used by `formatDate` etc~~
~~`convertLocalToUTCDateTime` takes the local date and returns what that date is in UTC.
Currently some of the daylight savings tests for this are failing when run with Travis so I'm looking into that.~~
After some discussion it was decided to do the following:
`convertUTCToLocalDateTime` takes an object representing a UTC date/time and returns an object representing a date/time in the local timezone corresponding to the `data-timezone` identifier (e.g., `America/Toronto`)
`convertLocalToUTCDateTime` take an object representing …

Add convertUTCToLocalDateTime and convertLocalToUTCDateTime

---

lib/common.js
lib/dateTime.js
test/common.js
test/dateTime.js

This mirrors the monolith logic from the [corresponding PR there](https://git.dev.d2l/projects/CORE/repos/lms/pull-requests/7438/overview).
We're now ignoring the AM/PM designators and time format that comes in from the "overrides", because it'll be incorrect. This is OK, since there's no way for the user to override these things.

Constructing hour format string based on 24-hour clock setting

---

lib/common.js
test/common.js

This PR adds `data-oslo` parsing, which will enable BrightspaceUI/core to opt into Oslo features when supported by the LMS.
I couldn't run the tests locally, on my branch or on unchanged master:
```
ppaskaris@KDX1-PPASKARIS:/c/D2L/aux-src/intl (master)
$ npm test
> @brightspace-ui/intl@3.0.6 test C:\D2L\aux-src\intl
> npm run lint -s && npm run test:unit -s
[test]
[test] TimeoutError: waiting for function failed: timeout 60000ms exceeded
[test]     at new WaitTask (C:\D2L\aux-src\intl\node_modules\puppeteer\lib\DOMWorld.js:549:28)
[test]     at DOMWorld.waitForFunction (C:\D2L\aux-src\intl\node_modules\puppeteer\lib\DOMWorld.js:454:12)
[test]     at Frame.waitForFunction (C:\D2L\aux-src\intl\node_modules\puppeteer\lib\FrameManager.js:657:28)
[test]     at Page.waitForFunction …
```

Add data-oslo parsing

---

lib/number.js
test/number.js

I had mistakenly thought that custom group sizes -- including group sizes of zero -- weren't possible from the LMS. But they are via user account settings.
Without this support, group sizes of zero are formatted using a comma as a separator resulting in "1,000" instead of "1000" which in legacy fails to parse.

handling group sizes again

---

lib/dateTime.js
test/dateTime.js

A bug was found when running the tests in brightspaceUI/core in edge legacy where `convertLocalToUTCDateTime` was not working. It turns out that `Date.parse` doesn't work well in edge legacy when timezone is formatted like `GMT+8:45` and requires a timezone string more like `YYYY-MM-DDTHH:mm:ss(+|-)HH:MM` in that case (it does work fine with timezones like `EST` - when timezone is a full hour (e.g., -5) it returns more of a string format, whereas when it is something like -9.5 it returns that `GMT-9:30` format where the problem lies).

Edge (legacy): Date.parse bug

---

lib/common.js
test/common.js

This PR adds the `version` property to the Oslo configuration, which enables the client to maintain its cache.

Add version prop to oslo config

---

lib/dateTime.js
package.json
test/dateTime.js

I noticed the following behavior when using `formatDateString` to parse `Tue Feb 27 2018 00:00:00 GMT-0500 (Eastern Standard Time)`.
In chrome:
Becomes `02/27/2018, 24:00:00 EST` (INCORRECT)
In Firefox:
Becomes `02/27/2018, 00:00:00 EST` (CORRECT)
This 24hr time was causing dates to appear as the next day (e.g., would be displayed as Feb 28, 2018 12 AM)
I found this thread https://support.google.com/chrome/thread/29828561?hl=en that mentions this and a reply suggest to use `hourCycle: h23` and remove `hour12`, which does seem to fix it in my use case.

Bug fix: use hourCycle instead of hour12

---

package.json

Stacey smartly noticed that because the action wasn't using `--no-save` these were getting added.

fix: removing dependencies

---

lib/dateTime.js

Bermuda is also in AST/ADT and its name started with `Atlantic` so I added the check for that as well. For the other duplicates I verified what region(s) they were used in and modified to check for the simpler one in the if statement just in case.

fix: also check for Atlantic region for AST and ADT

---

README.md
lib/dateTime.js
test/dateTime.js

No code was actually changed, just moved around. The formatTime/parseTime etc functions are not technically in order but they're paired up nicely so I left them as is (though open to moving them as well). Most of the reorganization was with the helper functions.

cleanup: remove WIP warning from README, alphabetize functions

---

lib/number.js
test/number.js

Dealing with operations on floating point numbers in JavaScript is pretty weird -- the common example being `0.1 + 0.2 !== 0.3`. The reason for this of course is that precision gets lost in the conversion from base 10 to binary.
This appeared as a bug in our new numeric input, where if a precision of 15 digits was requested, `5.2` gets instantly reformatted as `5.2000000000000002` -- not ideal.
The [general advice around this](https://www.avioconsulting.com/blog/overcoming-javascript-numeric-precision-issues#:~:text=In%20Javascript%2C%20all%20numbers%20are,the%20sign%20in%20bit%2063.) is to multiple by 10 to the power of whatever precision you need, do the operation (like addition/subtraction, etc.) and then divide back by that same value.
So that's the solution I went with here when it's …

fixing floating point precision error when formatting decimals

---

lib/number.js
test/number.js

We're still seeing floating point rounding problems when the number of digits + the requested precision (15 digits from the LMS) exceeds the maximum integer size in JavaScript (`2^53`). For example, `99,999` with a precision of 15 digits resulted in `99,000 x 10^15` being greater than `2^53` so rounding occurs and precision is lost.
So I decided to go back to the drawing board and do something with our Intl stuff that I've wanted to do for a while -- just call into the native `Intl.MessageFormat` APIs! What a concept! The trick here is that we just pass in a known locale (the `en-US` one) where we know the decimal separator will be a period. Then we can grab the stuff before/after the period and re-format it using our crazy rules.
Bonus: it supports max/min fraction digits and handles all …

fix: switching to use native formatNumber API

---

README.md
lib/number.js
test/number.js

Within our number input web component, we've decided that we'd like to suppress showing the thousand separators in the input itself. These can be confusing to see in an input, especially when you're trying to change a value by adding/removing digits -- in these cases you need to fix where the thousand separators are before it'll validate.
This is why it's not common to see thousand separators in number inputs -- `<input type="number">` doesn't show them, and tools like Excel/Google Sheets only show them where a number is rendered, not where it's inputted.
This change adds an option to suppress thousand separators from `formatNumber()` -- it follows the same naming convention as the native [Intl NumberFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/I …

feat: adding a useGrouping option for number formatting

---

lib/number.js

There's a weird issue with `Intl.NumberFormat` that Apple introduced in Safari 14.1 that only affects macOS Mojave users (10.14). If you use the `signDisplay` option, [it throws an exception](https://github.com/WebKit/WebKit/blob/9cb35748705901155cb6d83963671c791046c035/Source/JavaScriptCore/runtime/IntlNumberFormat.cpp#L586) with the message `Failed to initialize NumberFormat since used feature is not supported in the linked ICU version`. This is not a problem on later versions of macOS.
Our usage here of the `signDisplay` option wasn't necessary anyway, since we take the absolute value of the number on the line above and then add in the negative symbol later anyway.
Apple [has addressed the issue](https://trac.webkit.org/changeset/278697/webkit), but it's not clear when that will be …

fix Safari 14.1 NumberFormat issue

---

README.md

I found that the 'medium' format actually maps to 'MMM d, yyyy' instead of 'MMMM d, yyyy' for English (and a few other languages). Just fixing the docs to match the implementation

fix: correct readME about medium format

---

README.md
lib/dateTime.js
test/dateTime.js

I would like to propose we add the following methods to the date time helpers:
1. `formatDateFromTimestamp`
2. `formatTimeFromTimestamp`
This seems consistent with the other formatting helpers which provide options for formatting the date or time individually and allows more flexibility for consumers using timestamps.
Another thought I had was to expose the `parseLocalDateTimeFromTimestamp` method and allow consumers to format the resulting `Date` object however they want. I'm not sure if that would be a preferable option in this case.

Added helpers for formatting timezones

---

lib/common.js

I ran into this in core -- `reset()` is only ever called from tests and is intended to reset things back to "normal" in between tests that might manipulate the document's language settings so they're all starting from a consistent state. The issue is that if the page initially loads with a particular language, `reset()` actually sets it to `null`. This fixes that.

fix: reset should revert to initial value

---

README.md
lib/list.js
test/index.html
test/list.js

This PR adds a utility for getting the correct list separator (e.g. ", ") for the current locale. This is required for the new `object-property-list` component:
> To get the object-property-list component to read correctly on screen-readers, we render "hidden commas" between items. For this to work correctly across locales, we need a way to determine the appropriate list separator for the current locale.
Rally: https://rally1.rallydev.com/#/?detail=/userstory/641658870535&fdp=true

feat: Add list getSeparator utility

---

lib/common.js

Exposing the localized locale names for our supported locales. This will make rendering a "language picker" dropdown easier.

feat: add locale names

---

.github/CODEOWNERS
lib/common.js
lib/dateTime.js
test/common.js

We're [removing core's cache](https://github.com/BrightspaceUI/core/pull/3986) of the date/time descriptor because it had no way to know when to invalidate it when the language changed.
This re-adds the caching in a better place -- at the source!

feat: cache date/time descriptor

---

.gitignore
lib/common.js
lib/dateTime.js
lib/number.js
package-lock.json

[US156955](https://rally1.rallydev.com/#/?detail=/userstory/720543634719&fdp=true): Intl
Adds Maori support to date/time, numbers, and supported lang/locales. Also moves some commonly repeated lang/locale lists into Intl, which can be imported from here going forward.
More list changes to come later.

Add Maori support

---

package.json

There are some edge cases where imports from this library fail because it thinks it's a commonJS module. Frankly, I'm not sure why there hasn't been more issues without this declared.

Add type to package.json

---

lib/common.js

This is to align things with what's in `LANG_LANGUAGES` in the LMS.

fix: align with LMS naming

---

.github/workflows/release.yml

The previous release timed out because it took too long to add comments to all the PRs that were included (mostly Dependabot).  It didn't end up publishing to NPM.

fix: update release timeout

---

.eslintrc.json
demo/index.html
helpers/getLocalizeResources.js
lib/localize.js
package-lock.json
package.json
test/localize.test.js

[GAUD-6476](https://desire2learn.atlassian.net/browse/GAUD-6476): Extract generic `LocalizeMixin` functionality to a class in @brightspace-ui/intl
A straight move from the temporary core localize files, plus moving `getLocalizeResources` here. We'll update the core version to a shell that exports this one.
[GAUD-6476]: https://desire2learn.atlassian.net/browse/GAUD-6476?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add localize

---

package-lock.json
package.json
test/getLocalizeResources.test.js

Moves over `getLocalizeResources` tests from `core`

Move getLocalizeResources tests

---

.github/dependabot.yml
lib/PluralRules.js
lib/localize.js
package-lock.json
package.json
test/PluralRules.test.js
test/localize.test.js

Support for Māori across browsers is inconsistent at best. Specifically for `Intl.PluralRules` (which is relied upon by `formatjs` to render `plural` arguments), no browsers have (proper) native support for Māori's plural categories. The `@formatjs/intl-pluralrules` polyfill also does not have data for Māori, and provides no value otherwise as `Intl.PluralRules` is well supported at this point.
We can rely on native `Intl.PluralRules` as long as we can shim locale data into it for `formatjs` to use. So, that's what we do here.

Add PluralRules locale data shimming

---

lib/localize.js
test/localize.test.js

Each instance of the `Localize` class should have its own (as in `hasOwn`) `localize` method to store its resources and other localization-related state.
This is not applied to the `LocalizeClass` so that other uses, like for component mixins, can continue to share resources per-component. There is some light additional work to be done in `core` to fully take advantage of this because it's currently re-fetching for each element even if the component has its resources. However, that can be done separately from this change.
Using [`getPrototypeOf`/`super` instead of `bind`](https://jsbenchmark.com/#eyJjYXNlcyI6W3siaWQiOiI1am9KT00zUENlQXdFUTkzRms5RVgiLCJjb2RlIjoiREFUQS5iLmIoKTsiLCJuYW1lIjoiRmluZCA5OSIsImRlcGVuZGVuY2llcyI6W119LHsiaWQiOiJkXzBjTEVYZUh6aTFhdHJqdnpFRHciLCJjb2RlIjoiREFUQS5jLmIoKTsi …

Create instance own localize method

---

.eslintrc.json
README.md
intl.serge.json
lang/ar.js
lang/cy.js
lang/da.js
lang/de.js
lang/en-gb.js
lang/en.js
lang/es-es.js
lang/es.js
lang/fr-fr.js
lang/fr.js
lang/hi.js
lang/ja.js
lang/ko.js
lang/nl.js
lang/pt.js
lang/sv.js
lang/tr.js
lang/zh-cn.js
lang/zh-tw.js
lib/localize.js
package.json
test/localize.test.js

I had some trouble figuring out how best to integrate this, so definitely interested in feedback and other ideas.
The big downside to this approach is that every component that wires up to a localizer via the `LocalizeMixin` is going to have these "common" terms merged into their collection. That's why I needed to use the `intl-common` prefix on all their keys to avoid a potential collission.
~It also means that the common terms will **always** be fetched once on every page, even if they're not used. Both `localize` and `localizeHTML` are synchronous, so I couldn't think of a way to defer the loading of the common stuff.~ That's no longer true now that `loadCommon: true` must be set in the config.

feat: add ability to localize common characters

---

lib/localize.js

Small tweak to this after trying to consume if from core in a component using `LocalizeMixin`. `LocalizeMixin` checks the value of `_hasResources` to defer rendering until the resources have loaded.

fix: if loadCommon then there are resources

---

lib/common.js

[GAUD-7412](https://desire2learn.atlassian.net/browse/GAUD-7412): Add `haw` as supported language in `brightspace-ui/intl`
Adds `haw`/`haw-us` as a supported lang/locale. More data for dates/times, numbers etc. will be added separately.
[GAUD-7412]: https://desire2learn.atlassian.net/browse/GAUD-7412?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add Hawaiian to supported languages

---

lib/common.js

[GAUD-7600](https://desire2learn.atlassian.net/browse/GAUD-7600): intl: Filter bad locales and fail gracefully
In addition to the invalid `en-US@posix` locale, some environments have an empty string. This fix is in addition to [setting the `LANG` env var](https://github.com/BrightspaceUI/testing/pull/630/files), which is preferable to these fallbacks and failures.
- Fall back to `defaultLocale`
- Filter out [invalid locales](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl#locales_argument)
- Fail gracefully via try-catch
[GAUD-7600]: https://desire2learn.atlassian.net/browse/GAUD-7600?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Filter out bad locales and fail gracefully

---

lib/document-locale-settings.js
test/common.test.js

Fixing a regression from #248.
For better or worse, `localize-behavior` is [directly modifying](https://github.com/BrightspaceUI/localize-behavior/blob/main/test/d2l-localize-behavior.test.js#L326) the locale setting's timezone name and identifier. Because those are both just pointers to `DEFAULTS`'s references, in doing so it's actually changing the `DEFAULTS`. Then when `reset()` does an `Object.assign` they propagate.
The fix here is to do a deep copy of `DEFAULTS` during `reset()`.
This will fix the [failing CI in localize-behavior](https://github.com/BrightspaceUI/localize-behavior/pull/67).

GAUD-8233: deep copy defaults upon reset
